api_platform:
    title: Blog RAD API
    description: Follow the Rapid Application Development concept with API Platform and doctrine
    version: 0.0.1
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
