
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: blograd
        POSTGRES_PASSWORD: lionel
        POSTGRES_USER: lionel


###< doctrine/doctrine-bundle ###
