## AJout nouveau user

POST https://localhost:8000/api/users
Content-Type: application/ld+json

{
  "email": "jordy.luettgen@example.org",
  "roles": [
    "ROLE_USER"
  ],
  "password": "azertyuiop"
}

### Authentification
POST https://localhost:8000/auth
Content-Type: application/ld+json

{
    "email": "vanessa08@example.com",
    "password": "azertyuiop"
}